### PR TITLE
New website design

### PR DESCRIPTION
**Pull request by pepibumur**
[Main.pdf](https://github.com/tuist/design/files/2946850/Main.pdf)
[Blog.pdf](https://github.com/tuist/design/files/2946844/Blog.pdf)
[Blog post.pdf](https://github.com/tuist/design/files/2946846/Blog.post.pdf)

### CODE REVIEW

**Comment by pepibumur** [comment]
Would you mind having a look at the designs and let me know your first impressions @tuist/core ?

**Comment by ollieatkinson** [comment]
Some of the text looks clipped, but I will assume that's because of the PDF rendering.

Few notes:

- The design is clean, I like the header - I feel like a subtle animation (maybe the wave slowly animates) would really spice it up.
- Not too keen on the blog icon, doesn't seem to fit with the other icons.
- I think a custom font for the word "tuist" might give it some character.

--- 

I'm not a designer, but I will put this in-front of a few friends to get their opinions - thanks for doing this @pepibumur, really going to help with the mainstream adoption of tuist!

**Comment by pepibumur** [comment]
> The design is clean, I like the header - I feel like a subtle animation (maybe the wave slowly animates) would really spice it up.

I'll add some subtle animations 👍.

> Not too keen on the blog icon, doesn't seem to fit with the other icons.

I'll come up with something else for the icon. I felt like introducing a emoji somewhere but it might not be the right fit.

> I think a custom font for the word "tuist" might give it some character.

Like a Serif font?

Thanks for the feedback @ollieatkinson

**Comment by kwridan** [comment]
Nice work putting this together! Looks very well polished! No easy feat.

Reviewing visual designs is tougher than code reviews - it’s very subjective. With that disclaimer in mind here are some thoughts / suggestions 🙂

## Visual Layout 

- Echo Ollie’s comment, very clean! The header is 👍
- Color scheme looks really nice - You managed to pull off that green in the middle too 😛

## Icons

- The icons are a nice addition to highlight each point
- For Xcode workspace perhaps we could use something familiar? 

(My poor attempts at design)

27B46426-58A4-414A-948E-2E238AB9DFA4

AEB3743E-D31D-404F-833C-B156F39B9180

 - For the robot icon, some alternatives to emphasize Tuist is the tool doing the heavy lifting

F99AB8AC-C9EB-44C8-BB50-873937A9F42C

# Structure

- How about starting with **“What is Tuist?”** instead of **“Why Tuist”**?. For someone reading this for the first time, their first question is probably what is this rather why. 
- For the "what are you waiting for section" - possibly "Give it a go" / "Test it out" + the install one liner 
  - Wording wise, possibly approaching it from a positive sentiment e.g. "Start saving time" / "Save time by leveraging Tuist"

# Copy

Copy is hard! 

Seeing the target audience for the website is mostly developers, the pitch (so to speak) is perhaps best demonstrated with code / command examples and some brief explanations. 

An example: 

----
### How does it work?

`tuist generate`
- Reads your project definitions from manifest files
- Lints the definitions and flags issues early on
- Creates a graph to resolve your target dependencies
- Generates Xcode projects with the appropriate settings and build phases 

Check out the Documentation for more details on all available commands!

----

If there's room for a project manifest there, seeing one could be a big selling point

Screen Shot 2019-03-09 at 11 16 20 PM

**Pull request merged**
